
export const UNLEASH_THE_MATRIX = 'UNLEASH_THE_MATRIX'
export const FILL_CELL = 'FILL_CELL'
export const SELECT_CELL = 'SELECT_CELL'
export const ERASE_ALL_MISTAKES = 'ERASE_ALL_MISTAKES'
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'